version: '3'

services:
  php:
    build: ./docker/php
    links:
      - postgres
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html

  nginx:
    image: nginx:stable
    ports:
      - 85:80
    links:
      - php
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fitness_club
